//
// Created by fanboyan on 2025/6/11.
//

#ifndef DREAM_ENGINE_SYMBOLS_H
#define DREAM_ENGINE_SYMBOLS_H

#define NANOSECONDS_PER_SECOND 1000000000
#define DEFAULT_WINDOW_WIDTH 1280
#define DEFAULT_WINDOW_HEIGHT 720
#define DEFAULT_WINDOW_TITLE "Hello DreamEngine!"
#define DEFAULT_WINDOW_FRAME_RATE 60
#define NONE 0

#endif //DREAM_ENGINE_SYMBOLS_H
